export { default as home } from './Homepage'
export { default as NotFoundpage } from './NotFoundpage'
export {  default as Searchpage } from './Searchpage'
export { default as  Showpage } from './Showpage'
export { default as Showspage } from './Showspage'